# 错误哲学和返回值

## 1. 错误哲学

在 Rust 中，错误处理是一个非常重要的概念。Rust 的错误处理哲学是：

- 可恢复错误：通常用于从系统全局角度来看可以接受的错误，比如文件不存在、网络连接中断等。
- 不可恢复错误：通常用于程序内部错误，比如数组越界、空指针等。

Rust 也有自己的方式：`Result<T, E>` 和 `panic!` 宏。

## panic 深入剖析

`panic!` 宏是 Rust 的错误处理机制之一，它会导致程序崩溃并输出错误信息。`panic!` 有两种模式：

- 被动触发：当程序遇到不可恢复错误时，会自动触发 panic。
- 主动触发：当程序遇到不可恢复错误时，可以使用 `panic!` 主动触发 panic。

切记，一定是不可恢复的错误，才调用 panic! 处理，你总不想系统仅仅因为用户随便传入一个非法参数就崩溃吧？所以，只有当你不知道该如何处理时，再去调用 panic!.

```
thread 'main' panicked at 'crash and burn', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

这里包含了两个信息：

- main 函数所在的线程崩溃了。
- 再加上一个环境变量，可以显示详细的调用栈信息。

## panic 时的终止方法

当 panic 发生时会有两种方式终止程序：

- 栈展开
- 直接终止

默认情况下，Rust 会选择栈展开，这样可以保证程序在 panic 时，可以释放资源。但是，如果你想要快速终止程序，可以使用 `panic=abort` 参数。

## 何时该使用 panic!

### 示例、原型、测试

这几个场景下，需要快速地搭建代码，错误处理会拖慢编码的速度，也不是特别有必要，因此通过 unwrap、expect 等方法来处理是最快的。

同时，当我们回头准备做错误处理时，可以全局搜索这些方法，不遗漏地进行替换。

### 你确切的知道你的程序是正确时，可以使用 panic

因为 panic 的触发方式比错误处理要简单，因此可以让代码更清晰，可读性也更加好，当我们的代码注定是正确时，你可以用 unwrap 等方法直接进行处理，反正也不可能 panic

### 可能导致全局有害状态的时候

有害状态：

- 非预期的错误
- 后续的代码无法继续执行
- 内存安全问题

## result and ?

`Result<T, E>` 是 Rust 的错误处理机制之一，它是一个枚举类型，有两个成员：

- Ok(T)：表示成功，包含成功的返回值。
- Err(E)：表示失败，包含失败的返回值。

`?` 是 Rust 的语法糖，用于简化错误处理的代码。`?` 只能用于返回 `Result` 类型的函数，如果函数返回 `Ok(T)`，则 `?` 会返回 `T`；如果函数返回 `Err(E)`，则 `?` 会提前返回 `Err(E)`。

## 何时该使用 Result

```
error[E0308]: mismatched types
 --> src/main.rs:4:18
  |
4 |     let f: u32 = File::open("hello.txt");
  |                  ^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found enum
`std::result::Result`
  |
  = note: expected type `u32`
             found type `std::result::Result<std::fs::File, std::io::Error>`

```

这里我们可以看到，`File::open` 返回的是一个 `Result` 类型，而我们却直接将其赋值给了 `u32` 类型，这显然是不对的。

std::fs::File::open 的返回值是一个 Result 类型，而不是一个 u32 类型，这就是我们需要使用 Result 的原因.

### 何时该使用 Result

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => panic!("Problem opening the file: {:?}", other_error),
        },
    };
}
```

这里我们可以看到，我们使用了 nested match 来处理 Result 类型，这样我们就可以根据不同的情况来处理不同的错误，这样就可以更好地处理错误。

- 当文件打开失败时，返回错误
  - 如果文件不存在，则创建文件，否则返回错误

### unwrap 和 expect

`unwrap` 和 `expect` 是 `Result` 类型的两个方法，用于简化错误处理的代码。

- `unwrap`：如果 `Result` 类型是 `Ok(T)`，则返回 `T`；如果是 `Err(E)`，则触发 panic。
- `expect`：与 `unwrap` 类似，但是可以自定义 panic 的错误信息。

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").unwrap();
    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
```

### panic! 和 unwrap 的区别

- `panic!`：主动触发 panic，用于处理不可恢复错误。
- `unwrap`：用于处理可恢复错误，如果是不可恢复错误，则会触发 panic。

### 传播错误

在 Rust 中，我们可以使用 `?` 来传播错误，这样可以简化错误处理的代码。

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt")?;
}
```

这里我们可以看到，我们使用 `?` 来传播错误，这样可以简化错误处理的代码。
其实 ? 就是一个宏，它的作用跟上面的 match 几乎一模一样。 ? 会自动将 Result 类型的 Ok(T) 返回 T，将 Err(E) 返回 Err(E)。
还能链式调用，这样就可以更好地处理错误。

### ? 用于 Option 的返回

`?` 也可以用于 Option 的返回，如果 Option 是 `Some(T)`，则返回 `T`；如果是 `None`，则返回 `None`。

```rust
fn first(arr: &[i32]) -> Option<&i32> {
   let v = arr.get(0)?;
   Some(v)
}

```

### 常犯的错误

- 忘记使用 `?` 传播错误。
- 使用 `unwrap` 处理不可恢复错误。

